# Generated by Django 5.2.4 on 2025-07-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0002_restaurant_product_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='discription',
            field=models.TextField(default='adiss ababa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
