# Generated by Django 5.2.4 on 2025-07-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0004_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image1', models.ImageField(upload_to='food_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='food_images/')),
            ],
        ),
    ]
