# Generated by Django 5.2.4 on 2025-09-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0006_orderitem_status_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
    ]
