# Generated by Django 5.2.4 on 2025-09-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0010_alter_restaurant_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='owner',
        ),
    ]
