# Generated by Django 5.2.4 on 2025-09-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryApp', '0011_remove_restaurant_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
